baseURL = 'https://blackpiratex.com'
defaultContentLanguage = 'en-us'
locale = 'en-us'
title = 'BlackPirateX'
theme = 'typography-minimal'

[params]
  author = "Sudip"
  tagline = "Welcome to my website"
  github = "https://github.com/blackpiratelive"
  trakt_username = "bpx"
  trakt_client_id = "a52c9cdfbdddb8ba4ffe12a70c5591e05c985eddea6cd0fb53f998fee6c59dd0"
  tmdb_api_key = "61c9bbbefe48beed3b4f02f0cc4794e7"

[menus]
  [[menus.main]]
    name = 'Home'
    pageRef = '/'
    weight = 10

  [[menus.main]]
    name = 'Thoughts'
    pageRef = '/thoughts'
    weight = 10

  [[menus.main]]
    name = 'Blog'
    pageRef = '/blog'
    weight = 20

  [[menus.main]]
    name = 'Gallery'
    pageRef = '/gallery'
    weight = 20

  [[menus.main]]
    name = 'Book Notes'
    pageRef = '/books'
    weight = 20

  [[menus.main]]
    name = 'Cinema'
    pageRef = '/movies'
    weight = 20

  [[menus.main]]
    name = 'About'
    pageRef = '/about'
    weight = 15

[outputs]
  home = ["HTML", "RSS", "ATOM", "JSON"]
  section = ["HTML", "RSS", "ATOM", "JSON"]
  taxonomy = ["HTML", "RSS", "ATOM"]
  term = ["HTML", "RSS", "ATOM"]

[mediaTypes]
  [mediaTypes."application/atom+xml"]
    suffixes = ["xml"]

[outputFormats]
  [outputFormats.ATOM]
    mediaType = "application/atom+xml"
    baseName = "atom"
    isPlainText = false

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
    [markup.goldmark.extensions]
      footnote = true

[security]
  enableInlineShortcodes = false
  allowContent = ['^text/html$', '^text/markdown$']
  [security.funcs]
    getenv = ['^HUGO_', '^CI$', '^VERCEL$']
