baseURL = 'https://blackpiratex.com'
languageCode = 'en-us'
title = 'BlackPirateX'
theme = 'suckless'

[menus]
  [[menus.main]]
    name = 'Home'
    pageRef = '/'
    weight = 10

  [[menus.main]]
    name = 'Thoughts'
    pageRef = '/thoughts'
    weight = 10

  [[menus.main]]
    name = 'Blog'
    pageRef = '/blog'
    weight = 20

  [[menus.main]]
    name = 'Gallery'
    pageRef = '/gallery'
    weight = 20

  [[menus.main]]
    name = 'Book Notes'
    pageRef = '/books'
    weight = 20

  [[menus.main]]
    name = 'Uses'
    pageRef = '/uses'
    weight = 20

  [[menus.main]]
    name = 'search-icon'
    pageRef = '/search'
    weight = 30
    [menus.main.params]
      icon = 'search'

  [[menus.main]]
    name = 'on-this-day-icon'
    pageRef = '/on-this-day'
    weight = 31
    [menus.main.params]
      icon = 'calendar'

[outputs]
  home = ["HTML", "RSS", "JSON"]
